var annotated_dup =
[
    [ "compat_list", "structcompat__list.html", "structcompat__list" ],
    [ "handler_descriptor", "structhandler__descriptor.html", "structhandler__descriptor" ],
    [ "ieee1394", "structieee1394.html", "structieee1394" ],
    [ "pci_bar_info", "structpci__bar__info.html", "structpci__bar__info" ],
    [ "pci_bridge_callback", "structpci__bridge__callback.html", "structpci__bridge__callback" ],
    [ "pci_bridge_callback_list", "structpci__bridge__callback__list.html", "structpci__bridge__callback__list" ],
    [ "pci_config_address_t", "structpci__config__address__t.html", "structpci__config__address__t" ],
    [ "pci_config_mmio_data", "structpci__config__mmio__data.html", "structpci__config__mmio__data" ],
    [ "pci_config_space", "structpci__config__space.html", "structpci__config__space" ],
    [ "pci_device", "structpci__device.html", "structpci__device" ],
    [ "pci_driver", "structpci__driver.html", "structpci__driver" ],
    [ "pci_match_number_list", "structpci__match__number__list.html", "structpci__match__number__list" ],
    [ "pci_monitor_host", "structpci__monitor__host.html", "structpci__monitor__host" ],
    [ "pci_monitor_log", "structpci__monitor__log.html", "structpci__monitor__log" ],
    [ "pci_monitor_options", "structpci__monitor__options.html", "structpci__monitor__options" ],
    [ "pci_monitor_time", "structpci__monitor__time.html", "structpci__monitor__time" ],
    [ "pci_msi", "structpci__msi.html", "structpci__msi" ],
    [ "remap_inf", "structremap__inf.html", "structremap__inf" ],
    [ "vga_func_data", "structvga__func__data.html", "structvga__func__data" ],
    [ "x540", "structx540.html", "structx540" ],
    [ "x540_config", "structx540__config.html", "structx540__config" ],
    [ "x540_hook_context", "structx540__hook__context.html", "structx540__hook__context" ],
    [ "x540_rdesc", "structx540__rdesc.html", "structx540__rdesc" ],
    [ "x540_tdesc", "structx540__tdesc.html", "structx540__tdesc" ]
];